# Generated by Django 4.2.2 on 2023-06-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("symbol", models.CharField(blank=True, max_length=40, unique=True)),
                ("coingecko_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentOHLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(help_text="Date of the OHLC")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=8, help_text="Opening price", max_digits=30
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=8, help_text="High price", max_digits=30
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=8, help_text="Low price", max_digits=30
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=8, help_text="Closing price", max_digits=30
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.instrument"
                    ),
                ),
            ],
        ),
    ]
