# Generated by Django 4.2.2 on 2023-06-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_investmentcheck_result_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
