# Generated by Django 4.2.2 on 2023-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_synchistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="synchistory",
            name="records_synced",
            field=models.IntegerField(default=0),
        ),
    ]
