# Generated by Django 4.2.2 on 2023-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_synchistory_records_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="synchistory",
            name="sync_type",
            field=models.CharField(
                choices=[("prices", "Prices"), ("trades", "Trades")],
                default="prices",
                max_length=10,
            ),
        ),
    ]
