# Generated by Django 4.2.2 on 2023-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_synchistory_sync_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="synchistory",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
