# Generated by Django 4.2.2 on 2023-06-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_synchistory_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="enable_dydx_trades",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_size", models.FloatField()),
                ("input_instr_price", models.FloatField()),
                ("input_base_price", models.FloatField()),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("date_opened", models.DateTimeField(auto_now_add=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "base_instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_positions",
                        to="api.instrument",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="api.instrument",
                    ),
                ),
            ],
        ),
    ]
