# Generated by Django 4.2.2 on 2023-06-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_instrument_enable_dydx_trades_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="dydx_market_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
