# Generated by Django 4.2.2 on 2023-06-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_instrument_dydx_market_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstrumentOHLC",
            new_name="CoingeckoInstrumentOHLC",
        ),
        migrations.CreateModel(
            name="DydxCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField(help_text="Date of the OHLC")),
                ("period_end", models.DateTimeField(help_text="Date of the OHLC")),
                ("resolution", models.CharField(blank=True, max_length=10)),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=8, help_text="Opening price", max_digits=30
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=8, help_text="High price", max_digits=30
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=8, help_text="Low price", max_digits=30
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=8, help_text="Closing price", max_digits=30
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.instrument"
                    ),
                ),
            ],
        ),
    ]
