# Generated by Django 4.2.2 on 2023-06-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_rename_instrumentohlc_coingeckoinstrumentohlc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_trades", models.BooleanField(default=False)),
            ],
        ),
    ]
