# Generated by Django 4.2.2 on 2023-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synchistory",
            name="sync_type",
            field=models.CharField(
                choices=[
                    ("prices", "Prices"),
                    ("trades", "Trades"),
                    ("dydx_candles", "DyDx Candles"),
                ],
                default="prices",
                max_length=20,
            ),
        ),
    ]
